# Generated by Django 5.1 on 2024-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('kcal', models.FloatField()),
                ('fats', models.FloatField()),
                ('carb', models.FloatField()),
                ('prot', models.FloatField()),
                ('fibe', models.FloatField()),
                ('sodi', models.FloatField()),
                ('ingr', models.TextField(default='[]')),
            ],
        ),
    ]
