# Generated by Django 5.1 on 2024-08-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
