# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2024-03-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('tipoDispositivo', models.CharField(default='Selecione', max_length=100)),
                ('marca', models.CharField(default='Selecione', max_length=255)),
                ('numeroCelular', models.CharField(default='', max_length=50)),
                ('numeroConta', models.CharField(default='', max_length=50)),
                ('usuario', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='Selecione', max_length=255)),
                ('valor', models.FloatField(default=0)),
                ('serial', models.CharField(default='', max_length=255)),
                ('reparos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reparo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('nome', models.CharField(default='', max_length=255)),
                ('dia', models.DateField()),
                ('preco', models.FloatField(default=0)),
            ],
        ),
    ]
