# Generated by Django 4.2.11 on 2024-07-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_dispositivo_patri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reparo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
