# Generated by Django 5.1 on 2024-08-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0004_remove_reparo_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparo',
            name='dispositivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario_app.dispositivo'),
        ),
    ]
